# Generated by Django 2.0.2 on 2018-03-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_lecture_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=124)),
                ('lectures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='exercises.Lecture')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exercises.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='lecture',
            field=models.ManyToManyField(through='exercises.Week', to='exercises.Lecture'),
        ),
    ]
