# Generated by Django 2.0.2 on 2018-03-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20180315_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': (('add_group', 'Can add group'),)},
        ),
    ]
